import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { network } from "hardhat";
import { privateKeyToAccount } from "viem/accounts";

import { deployCertificate } from "./deploy-certificate.js";

const LOCAL_CHAIN_ID = 31337;

/**
 * Hardhat test account #1 ("test test ... junk" mnemonic). The key is public:
 * it signs claim vouchers on the local chain only and never holds real funds.
 */
const LOCAL_CLAIM_SIGNER_PRIVATE_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";

/** The only file this script writes. Next.js loads it in `next dev` only. */
const WEB_ENV_PATH = new URL("../../apps/web/.env.development.local", import.meta.url);

const connection = await network.create();
if (connection.networkConfig.type !== "http") {
  // The in-process network also uses chain 31337, but it disappears when the script exits.
  throw new Error("deploy-local needs a running node: start `pnpm chain`, then run `pnpm deploy:local`");
}
const chainId = await (await connection.viem.getPublicClient()).getChainId();
if (chainId !== LOCAL_CHAIN_ID) {
  throw new Error(`deploy-local only targets the local Hardhat node (chain ${LOCAL_CHAIN_ID}), got chain ${chainId}`);
}

const claimSigner = privateKeyToAccount(LOCAL_CLAIM_SIGNER_PRIVATE_KEY);
const address = await deployCertificate(connection, claimSigner.address);

writeFileSync(
  WEB_ENV_PATH,
  [
    "# Generated by `pnpm deploy:local`: overwritten on every run.",
    "# Public Hardhat test values for the local chain. Never use these keys with real funds.",
    `NEXT_PUBLIC_CHAIN_ID=${LOCAL_CHAIN_ID}`,
    `NEXT_PUBLIC_NFT_CONTRACT_ADDRESS=${address}`,
    `CLAIM_SIGNER_PRIVATE_KEY=${LOCAL_CLAIM_SIGNER_PRIVATE_KEY}`,
    "",
  ].join("\n"),
);
console.log(`\nWrote ${fileURLToPath(WEB_ENV_PATH)}`);
console.log("Restart `pnpm dev` if it is running so Next.js picks up the new values.");
