import curriculum from '../../../../curriculum/lessons.json';
import modules from '../../../../curriculum/modules.json';
import type { LessonQuiz } from './steps';
import type { LessonCheck } from './validate';

export interface LessonExercise {
  /** Markdown; its `###` sections become the steps of the explanation (see steps.ts). */
  explanation: string;
  starterCode: string;
  checks: LessonCheck[];
  /** Optional questions shown between steps. */
  quizzes?: LessonQuiz[];
}

interface LessonBase {
  /** Lesson id, also the ERC-1155 token id of its certificate. */
  id: number;
  slug: string;
  title: string;
  difficulty: string;
  xp: number;
  /** Id of the module (curriculum/modules.json) the lesson belongs to. */
  module: string;
  /** One line on what the student builds, shown on the lesson card. */
  preview: string;
  /** Estimated time to complete the lesson, in minutes. */
  minutes: number;
}

/** Available lessons have an exercise; unavailable ones are listed as coming soon. */
export type Lesson = LessonBase &
  ({ available: true; exercise: LessonExercise } | { available: false; exercise?: undefined });

interface LessonContent {
  slug: string;
  difficulty: string;
  preview: string;
  minutes: number;
  exercise?: LessonExercise;
}

/** Web-only lesson content, keyed by lesson id. Ids, names and XP live in curriculum/lessons.json. */
const CONTENT: Record<number, LessonContent> = {
  1: {
    slug: 'hello-world',
    difficulty: 'Beginner',
    preview: 'A contract that stores a greeting anyone can read and change.',
    minutes: 10,
    exercise: {
      explanation: [
        '## Hello World with Arbitrum Stylus',
        '',
        'Stylus lets you write smart contracts in Rust. They compile to WebAssembly and run on Arbitrum next to Solidity contracts, with the same storage model and ABI.',
        '',
        '### Anatomy of a Stylus contract',
        '',
        '1. `sol_storage!` declares the storage with Solidity syntax: `type name;` per field.',
        '2. `#[entrypoint]` marks the struct that receives the calls.',
        '3. A `#[public]` impl block exposes its methods in the contract ABI.',
        '',
        '```rust',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Profile {',
        '        string name;',
        '    }',
        '}',
        '```',
        '',
        'Each field gets a typed storage accessor. A `string` field is a `StorageString`:',
        '',
        '- `self.name.get_string()` reads it as a `String`;',
        '- `self.name.set_str(value)` writes it.',
        '',
        '### Your task',
        '',
        '1. Give the contract a storage field called `greeting` that holds text.',
        '2. Make `get_greeting` return the stored greeting.',
        '3. Make `set_greeting` store the text it receives.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use alloc::string::String;',
        'use stylus_sdk::prelude::*;',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct HelloWorld {',
        '        // TODO: add a string field called greeting',
        '    }',
        '}',
        '',
        '#[public]',
        'impl HelloWorld {',
        '    pub fn get_greeting(&self) -> String {',
        '        // TODO: return the stored greeting',
        '        String::new()',
        '    }',
        '',
        '    pub fn set_greeting(&mut self, greeting: String) {',
        '        // TODO: store the greeting',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['string greeting;'],
          objective: 'Store a greeting text in the contract storage',
          hints: [
            'Storage fields are declared inside `sol_storage!`, in the `HelloWorld` struct, with Solidity syntax: the type, then the name.',
            'The Solidity type for text is `string` and the field is called `greeting`. End the declaration with a semicolon.',
            'Add `string greeting;` inside `pub struct HelloWorld { ... }`.',
          ],
          anchor: 'pub struct HelloWorld {',
        },
        {
          anyOf: ['self.greeting.get_string()'],
          objective: 'Return the stored greeting from get_greeting',
          hints: [
            'A `string` field is a `StorageString` accessor: you read it with a method instead of using it as a plain value.',
            '`StorageString` has a method that returns its contents as a Rust `String`: `get_string()`.',
            'Replace `String::new()` with `self.greeting.get_string()`.',
          ],
          anchor: 'pub fn get_greeting(',
        },
        {
          anyOf: ['self.greeting.set_str(greeting)', 'self.greeting.set_str(&greeting)'],
          objective: 'Save the new greeting in set_greeting',
          hints: [
            'Writing a storage field also goes through its accessor, and `set_greeting` already takes `&mut self`.',
            '`StorageString` is written with `set_str`, which takes the text to store.',
            'Add `self.greeting.set_str(greeting);` to the body of `set_greeting`.',
          ],
          anchor: 'pub fn set_greeting(',
        },
      ],
      quizzes: [
        {
          afterStep: "Anatomy of a Stylus contract",
          question: "How do you declare a string field called greeting inside sol_storage!?",
          options: ["greeting: String,", "string greeting;", "let greeting: String;"],
          answer: 1,
          explanation: "sol_storage! uses Solidity field syntax: the type, then the name, then a semicolon. Rust struct syntax does not work inside it.",
        },
      ],
    },
  },
  2: {
    slug: 'storage-state',
    difficulty: 'Beginner',
    preview: 'A counter you can read, increment and reset.',
    minutes: 10,
    exercise: {
      explanation: [
        '## Storage and State',
        '',
        'Contract state lives in storage slots, exactly like in Solidity. In `sol_storage!` each field is declared with its Solidity type and becomes a typed storage accessor in Rust:',
        '',
        '| Solidity field | Rust accessor | Read | Write |',
        '|---|---|---|---|',
        '| `uint256 count;` | `StorageU256` | `self.count.get()` | `self.count.set(value)` |',
        '| `address owner;` | `StorageAddress` | `self.owner.get()` | `self.owner.set(value)` |',
        '| `bool paused;` | `StorageBool` | `self.paused.get()` | `self.paused.set(value)` |',
        '| `mapping(address => uint256) balances;` | `StorageMap` | `self.balances.get(key)` | `self.balances.setter(key).set(value)` |',
        '',
        'Numbers use `U256` from `stylus_sdk::alloy_primitives`. It has constants such as `U256::ZERO` and `U256::from(1)` builds one from a Rust integer.',
        '',
        '```rust',
        'let next = self.count.get() + U256::from(1);',
        'self.count.set(next);',
        '```',
        '',
        '> **Overflow:** `+` and `-` on `U256` wrap around instead of reverting: `U256::MAX + U256::from(1)` is zero. Solidity 0.8 would revert. The Security pitfalls lesson of module 5 shows how to refuse it with `checked_add` and `checked_sub`.',
        '',
        'Methods that write storage take `&mut self`; read-only methods take `&self`.',
        '',
        '### Your task',
        '',
        'Build a counter:',
        '',
        '1. Store an unsigned 256-bit number called `count`.',
        '2. `get` returns the current count.',
        '3. `increment` adds one to the count.',
        '4. `reset` sets it back to zero.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{alloy_primitives::U256, prelude::*};',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Counter {',
        '        // TODO: add a uint256 field called count',
        '    }',
        '}',
        '',
        '#[public]',
        'impl Counter {',
        '    pub fn get(&self) -> U256 {',
        '        // TODO: return the count',
        '        U256::ZERO',
        '    }',
        '',
        '    pub fn increment(&mut self) {',
        '        // TODO: add 1 to the count',
        '    }',
        '',
        '    pub fn reset(&mut self) {',
        '        // TODO: set the count back to zero',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['uint256 count;'],
          objective: 'Store a number called count in the contract',
          hints: [
            'Declare the field inside `sol_storage!`, in the `Counter` struct, with Solidity syntax.',
            'A counter uses the Solidity type `uint256`. End the declaration with a semicolon.',
            'Add `uint256 count;` inside `pub struct Counter { ... }`.',
          ],
          anchor: 'pub struct Counter {',
        },
        {
          anyOf: ['-> U256 { self.count.get() }', '-> U256 { return self.count.get(); }'],
          objective: 'Return the current count from get',
          hints: [
            'A `uint256` field is a `StorageU256` accessor: read it instead of returning the field itself.',
            '`StorageU256` has a `get()` method that returns a `U256`.',
            'The body of `get` is only the read: `pub fn get(&self) -> U256 { self.count.get() }`.',
          ],
          anchor: 'pub fn get(&self)',
        },
        {
          anyOf: ['self.count.set(self.count.get() + U256::from(1))', 'self.count.set(self.count.get() + U256::from(1u8))'],
          objective: 'Increment the count by 1',
          hints: [
            'Read the current value, add one, then write the result back.',
            'Read with `get()`, build a one with `U256::from(1)` and write with `set(...)`.',
            'Write `self.count.set(self.count.get() + U256::from(1));` in `increment`.',
          ],
          anchor: 'pub fn increment(',
        },
        {
          anyOf: ['self.count.set(U256::ZERO)', 'self.count.set(U256::from(0))'],
          objective: 'Reset the count to zero',
          hints: [
            'Resetting is a write: store the value zero in the field.',
            '`U256` has a constant for zero: `U256::ZERO`.',
            'Write `self.count.set(U256::ZERO);` in `reset`.',
          ],
          anchor: 'pub fn reset(',
        },
      ],
      quizzes: [
        {
          afterStep: "Storage and State",
          question: "Which line writes a new value to a uint256 field called count?",
          options: ["self.count = value;", "self.count.write(value);", "self.count.set(value);"],
          answer: 2,
          explanation: "Storage fields are accessors, not plain values: read with get() and write with set(value).",
        },
      ],
    },
  },
  3: {
    slug: 'events-errors',
    difficulty: 'Intermediate',
    preview: 'A token transfer that reverts with a custom error and emits an event.',
    minutes: 15,
    exercise: {
      explanation: [
        '## Events and Errors',
        '',
        'Events tell the outside world what happened; errors revert a call with a reason that callers can decode. Stylus declares both with the `sol!` macro, using Solidity syntax, so they have the same ABI as their Solidity counterparts.',
        '',
        '### Events',
        '',
        '```rust',
        'sol! {',
        '    event Transfer(address indexed from, address indexed to, uint256 value);',
        '}',
        '```',
        '',
        'Emit one through the host with `self.vm().log(...)`:',
        '',
        '```rust',
        'self.vm().log(Transfer { from, to, value });',
        '```',
        '',
        '### Errors',
        '',
        'Declare the error in `sol!`, then wrap it in an enum that derives `SolidityError`:',
        '',
        '```rust',
        'sol! {',
        '    error Unauthorized(address caller);',
        '}',
        '',
        '#[derive(SolidityError)]',
        'pub enum VaultError {',
        '    Unauthorized(Unauthorized),',
        '}',
        '```',
        '',
        'A method that can fail returns `Result<T, VaultError>`. Returning `Err(...)` reverts the call with the encoded error:',
        '',
        '```rust',
        'return Err(VaultError::Unauthorized(Unauthorized { caller }));',
        '```',
        '',
        'The caller of the current call is `self.vm().msg_sender()`.',
        '',
        '### Your task',
        '',
        '1. In `sol!`, declare a `Transfer` event with the `from` and `to` addresses, both indexed, and a `value` amount, and an `InsufficientBalance` error with the `available` and `required` amounts.',
        '2. Let `TokenError` carry the `InsufficientBalance` error.',
        '3. In `send`, revert with `InsufficientBalance` when the sender holds less than `amount`.',
        '4. Emit `Transfer` once the balances are updated.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{',
        '    alloy_primitives::{Address, U256},',
        '    alloy_sol_types::sol,',
        '    prelude::*,',
        '};',
        '',
        'sol! {',
        '    // TODO: declare the Transfer event and the InsufficientBalance error',
        '}',
        '',
        '#[derive(SolidityError)]',
        'pub enum TokenError {',
        '    // TODO: add an InsufficientBalance variant',
        '}',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Token {',
        '        mapping(address => uint256) balances;',
        '    }',
        '}',
        '',
        '#[public]',
        'impl Token {',
        '    pub fn send(&mut self, to: Address, amount: U256) -> Result<(), TokenError> {',
        '        let from = self.vm().msg_sender();',
        '        let available = self.balances.get(from);',
        '        // TODO: return InsufficientBalance when available < amount',
        '',
        '        self.balances.setter(from).set(available - amount);',
        '        let received = self.balances.get(to);',
        '        self.balances.setter(to).set(received + amount);',
        '',
        '        // TODO: emit Transfer',
        '        Ok(())',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['event Transfer(address indexed from, address indexed to, uint256 value);'],
          objective: 'Declare a Transfer event with indexed from and to addresses and a value',
          hints: [
            'Events are declared in the `sol!` block with Solidity syntax, as in a Solidity contract.',
            'Mark both addresses `indexed`; the amount is a `uint256` named `value`.',
            'Add `event Transfer(address indexed from, address indexed to, uint256 value);` to `sol!`.',
          ],
          anchor: 'sol! {',
        },
        {
          anyOf: ['error InsufficientBalance(uint256 available, uint256 required);'],
          objective: 'Declare an InsufficientBalance error with the available and required amounts',
          hints: [
            'Custom errors are declared in `sol!` too, with the `error` keyword.',
            'Both parameters are `uint256`: `available` first, then `required`.',
            'Add `error InsufficientBalance(uint256 available, uint256 required);` to `sol!`.',
          ],
          anchor: 'sol! {',
        },
        {
          anyOf: ['InsufficientBalance(InsufficientBalance)'],
          objective: 'Let TokenError carry the InsufficientBalance error',
          hints: [
            'An error enum deriving `SolidityError` has one variant per `sol!` error.',
            'The variant has the same name as the error and wraps the error type.',
            'Add `InsufficientBalance(InsufficientBalance),` to `TokenError`.',
          ],
          anchor: 'pub enum TokenError {',
        },
        {
          anyOf: ['if available < amount {', 'if amount > available {'],
          objective: 'Check the balance before moving tokens',
          hints: [
            'The sender must hold at least `amount`: check it before any balance changes.',
            'Compare `available` with `amount` in an `if`, right after reading the balance.',
            'Add `if available < amount { ... }` after `let available = ...`.',
          ],
          anchor: 'let available = self.balances.get(from);',
        },
        {
          anyOf: ['Err(TokenError::InsufficientBalance(InsufficientBalance {'],
          objective: 'Revert when the balance is too low',
          hints: [
            'Returning an `Err` from a `#[public]` method reverts the call.',
            'Wrap an `InsufficientBalance { available, required }` value in the `TokenError::InsufficientBalance` variant.',
            'Inside the `if`, write `return Err(TokenError::InsufficientBalance(InsufficientBalance { available, required: amount }));`.',
          ],
          anchor: 'let available = self.balances.get(from);',
        },
        {
          anyOf: ['self.vm().log(Transfer {'],
          objective: 'Emit Transfer after the balances are updated',
          hints: [
            'Events are emitted through the host, which `self.vm()` returns.',
            'Pass a `Transfer` value to the host `log` method; its amount field is `value`.',
            'Before `Ok(())`, write `self.vm().log(Transfer { from, to, value: amount });`.',
          ],
          anchor: 'Ok(())',
        },
      ],
      quizzes: [
        {
          afterStep: "Events",
          question: "How does a stylus-sdk 0.10 method emit a Transfer event?",
          options: ["self.vm().log(Transfer { from, to, value })", "evm::log(Transfer { from, to, value })", "emit Transfer(from, to, value);"],
          answer: 0,
          explanation: "Events go through the host with self.vm().log(...). The evm module, and evm::log with it, was removed in stylus-sdk 0.10.",
        },
        {
          afterStep: "Errors",
          question: "What does returning Err(...) from a #[public] method do?",
          options: ["It logs the error and the call succeeds", "It reverts the call with the ABI-encoded error", "It panics and consumes all the gas"],
          answer: 1,
          explanation: "With an error enum deriving SolidityError, Err(...) reverts the call and callers can decode the error, like a Solidity custom error.",
        },
      ],
    },
  },
  4: {
    slug: 'erc20-token',
    difficulty: 'Intermediate',
    preview: 'The core of an ERC-20 token: supply, balances and transfers.',
    minutes: 20,
    exercise: {
      explanation: [
        '## ERC-20 Token',
        '',
        'ERC-20 is the standard interface of fungible tokens on EVM chains. A Stylus contract that exposes the same methods and events is a regular ERC-20 for wallets, explorers and other contracts.',
        '',
        '### Interface',
        '',
        '| Method | Returns |',
        '|---|---|',
        '| `total_supply()` | `U256`: tokens in existence |',
        '| `balance_of(account)` | `U256`: tokens held by `account` |',
        '| `transfer(to, value)` | `bool`: moves `value` from the caller to `to` |',
        '| `approve(spender, value)` | `bool`: lets `spender` move up to `value` |',
        '| `transfer_from(from, to, value)` | `bool`: spends an allowance |',
        '',
        'Stylus exposes snake_case Rust methods under their camelCase Solidity names (`total_supply` is `totalSupply` in the ABI).',
        '',
        '### Storage',
        '',
        '```rust',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Erc20 {',
        '        uint256 total_supply;',
        '        mapping(address => uint256) balances;',
        '        mapping(address => mapping(address => uint256)) allowances;',
        '    }',
        '}',
        '```',
        '',
        '### Your task',
        '',
        '1. Give the contract its three storage fields: `total_supply`, `balances` (per account) and `allowances` (per owner, then per spender).',
        '2. Make `total_supply` and `balance_of` return the stored values.',
        '3. `transfer` reverts with `InsufficientBalance` when the caller holds less than `value`, moves the tokens, emits `Transfer` and reports success.',
        '',
        '`approve` and `transfer_from` follow the same pattern with `allowances`; they are left for later.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{',
        '    alloy_primitives::{Address, U256},',
        '    alloy_sol_types::sol,',
        '    prelude::*,',
        '};',
        '',
        'sol! {',
        '    event Transfer(address indexed from, address indexed to, uint256 value);',
        '    event Approval(address indexed owner, address indexed spender, uint256 value);',
        '    error InsufficientBalance(address from, uint256 have, uint256 want);',
        '}',
        '',
        '#[derive(SolidityError)]',
        'pub enum Erc20Error {',
        '    InsufficientBalance(InsufficientBalance),',
        '}',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Erc20 {',
        '        // TODO: add total_supply, balances and allowances',
        '    }',
        '}',
        '',
        '#[public]',
        'impl Erc20 {',
        '    pub fn total_supply(&self) -> U256 {',
        '        // TODO: return the total supply',
        '        U256::ZERO',
        '    }',
        '',
        '    pub fn balance_of(&self, account: Address) -> U256 {',
        '        // TODO: return the balance of account',
        '        U256::ZERO',
        '    }',
        '',
        '    pub fn transfer(&mut self, to: Address, value: U256) -> Result<bool, Erc20Error> {',
        '        let from = self.vm().msg_sender();',
        '        // TODO: revert when from holds less than value,',
        '        // move value from from to to, emit Transfer and return Ok(true)',
        '        Ok(false)',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['uint256 total_supply;'],
          objective: 'Store the total supply',
          hints: [
            'Declare the field inside `sol_storage!`, in the `Erc20` struct, with Solidity syntax.',
            'A token amount is a `uint256`; the field is named `total_supply`.',
            'Add `uint256 total_supply;` to `pub struct Erc20 { ... }`.',
          ],
          anchor: 'pub struct Erc20 {',
        },
        {
          anyOf: ['mapping(address => uint256) balances;'],
          objective: 'Store the balance of each account',
          hints: [
            'A balance per account is a mapping from an address to an amount.',
            'Map `address` to `uint256` and name the field `balances`.',
            'Add `mapping(address => uint256) balances;` to the struct.',
          ],
          anchor: 'pub struct Erc20 {',
        },
        {
          anyOf: ['mapping(address => mapping(address => uint256)) allowances;'],
          objective: 'Store the allowance of each owner for each spender',
          hints: [
            'An allowance depends on two addresses, the owner and then the spender: nest one mapping in another.',
            'The outer key is the owner, the inner key the spender and the value an amount; name the field `allowances`.',
            'Add `mapping(address => mapping(address => uint256)) allowances;` to the struct.',
          ],
          anchor: 'pub struct Erc20 {',
        },
        {
          anyOf: ['self.total_supply.get()'],
          objective: 'Return the total supply',
          hints: [
            'Read the storage field instead of returning zero.',
            'A `uint256` field is read with `get()`.',
            'Replace `U256::ZERO` with `self.total_supply.get()`.',
          ],
          anchor: 'pub fn total_supply(',
        },
        {
          anyOf: ['self.balances.get(account)'],
          objective: 'Return the balance of an account',
          hints: [
            'Look the account up in the balances mapping.',
            'A mapping is read with `get(key)`; the key here is `account`.',
            'Replace `U256::ZERO` with `self.balances.get(account)`.',
          ],
          anchor: 'pub fn balance_of(',
        },
        {
          anyOf: ['Err(Erc20Error::InsufficientBalance(InsufficientBalance {'],
          objective: "Revert a transfer larger than the sender's balance",
          hints: [
            'Read the balance of `from` and compare it with `value` before moving anything.',
            'Return an `Err` wrapping `InsufficientBalance { from, have, want }` in the `Erc20Error::InsufficientBalance` variant.',
            'After `let have = self.balances.get(from);`, write `if have < value { return Err(Erc20Error::InsufficientBalance(InsufficientBalance { from, have, want: value })); }`.',
          ],
          anchor: 'let from = self.vm().msg_sender();',
        },
        {
          anyOf: ['self.vm().log(Transfer {'],
          objective: 'Emit Transfer when tokens move',
          hints: [
            'Events are emitted through the host, which `self.vm()` returns.',
            'Pass a `Transfer` value with `from`, `to` and `value` to the host `log` method.',
            'After updating the balances, write `self.vm().log(Transfer { from, to, value });`.',
          ],
          anchor: 'pub fn transfer(',
        },
        {
          anyOf: ['Ok(true)'],
          objective: 'Report a successful transfer',
          hints: [
            '`transfer` returns a `Result<bool, _>`, and the starter code reports a failure.',
            'An ERC-20 transfer returns `true` when it succeeds, wrapped in `Ok`.',
            'Replace `Ok(false)` with `Ok(true)`.',
          ],
          anchor: 'pub fn transfer(',
        },
      ],
      quizzes: [
        {
          afterStep: "Interface",
          question: "Under which name does the Rust method balance_of appear in the contract ABI?",
          options: ["balance_of", "BalanceOf", "balanceOf"],
          answer: 2,
          explanation: "Stylus exports snake_case Rust methods under camelCase Solidity names, so wallets see the standard ERC-20 balanceOf.",
        },
        {
          afterStep: "Storage",
          question: "How do you write the new balance of to in the balances mapping?",
          options: ["self.balances.setter(to).set(new_balance)", "self.balances.get(to).set(new_balance)", "self.balances[to] = new_balance"],
          answer: 0,
          explanation: "get(key) returns a copy of the value; setter(key) returns a writable handle to the entry, and set(value) stores it.",
        },
      ],
    },
  },
  5: {
    slug: 'defi-interaction',
    difficulty: 'Advanced',
    preview: 'A contract that calls into a DeFi protocol.',
    minutes: 25,
  },
  6: {
    slug: 'mappings',
    difficulty: 'Beginner',
    preview: 'A scoreboard that keeps a score per player and lets players clear their own.',
    minutes: 15,
    exercise: {
      explanation: [
        '## Mappings',
        '',
        'A mapping stores one value per key, like a Solidity `mapping`. Every key already exists and holds the zero value until it is written, so there is nothing to create first. Mappings have no length and their keys cannot be listed.',
        '',
        '### Declaring a mapping',
        '',
        'Declare it in `sol_storage!` with Solidity syntax, `mapping(KeyType => ValueType) name;`:',
        '',
        '```rust',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Club {',
        '        mapping(address => bool) members;',
        '        mapping(address => uint256) deposits;',
        '    }',
        '}',
        '```',
        '',
        'Each field becomes a `StorageMap` accessor: `members` maps an `Address` to a `bool`, `deposits` an `Address` to a `U256`.',
        '',
        '### Reading a mapping',
        '',
        '`get(key)` returns the value stored for a key:',
        '',
        '```rust',
        'let joined = self.members.get(account); // false if never written',
        'let total = self.deposits.get(account); // U256::ZERO if never written',
        '```',
        '',
        'An address that never interacted with the contract reads as zero, `false` or the empty value, so reading never fails.',
        '',
        '### Writing and deleting',
        '',
        '| Call | Effect |',
        '|---|---|',
        '| `insert(key, value)` | Stores `value` for `key`. |',
        '| `setter(key).set(value)` | The same, through a writable handle to the entry. |',
        '| `replace(key, value)` | Stores `value` and returns the previous one. |',
        '| `take(key)` | Returns the value and resets the entry to zero. |',
        '| `delete(key)` | Resets the entry to zero. |',
        '',
        'Writing needs `&mut self`:',
        '',
        '```rust',
        'pub fn join(&mut self, amount: U256) {',
        '    let account = self.vm().msg_sender();',
        '    self.members.insert(account, true);',
        '    let total = self.deposits.get(account) + amount;',
        '    self.deposits.insert(account, total);',
        '}',
        '',
        'pub fn leave(&mut self) {',
        '    let account = self.vm().msg_sender();',
        '    self.members.delete(account);',
        '}',
        '```',
        '',
        '### Nested mappings',
        '',
        'A mapping can hold another mapping, for example an allowance per owner and per spender:',
        '',
        '```rust',
        'mapping(address => mapping(address => uint256)) allowances;',
        '```',
        '',
        '`getter(owner)` returns the inner mapping to read from, `setter(owner)` the inner mapping to write to:',
        '',
        '```rust',
        'let allowed = self.allowances.getter(owner).get(spender);',
        'self.allowances.setter(owner).insert(spender, value);',
        '```',
        '',
        '### Your task',
        '',
        'Build a scoreboard:',
        '',
        '1. Give `Scoreboard` a storage field called `scores` that keeps a `uint256` score for every player address.',
        '2. `score_of` returns the score of `account`.',
        '3. `record` adds `points` to the score of the caller, `player`.',
        '4. `clear` removes the score of the caller.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{',
        '    alloy_primitives::{Address, U256},',
        '    prelude::*,',
        '};',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Scoreboard {',
        '        // TODO: add a mapping from player addresses to uint256 scores',
        '    }',
        '}',
        '',
        '#[public]',
        'impl Scoreboard {',
        '    pub fn score_of(&self, account: Address) -> U256 {',
        '        // TODO: return the score of account',
        '        U256::ZERO',
        '    }',
        '',
        '    pub fn record(&mut self, points: U256) {',
        '        let player = self.vm().msg_sender();',
        '        // TODO: add points to the score of player',
        '    }',
        '',
        '    pub fn clear(&mut self) {',
        '        let player = self.vm().msg_sender();',
        '        // TODO: remove the score of player',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['mapping(address => uint256) scores;'],
          objective: 'Keep a score for every player address',
          hints: [
            'One value per address is a mapping, declared inside `sol_storage!` in the `Scoreboard` struct.',
            'The key type is `address`, the value type `uint256`, and the field is called `scores`.',
            'Add `mapping(address => uint256) scores;` inside `pub struct Scoreboard { ... }`.',
          ],
          anchor: 'pub struct Scoreboard {',
        },
        {
          anyOf: ['self.scores.get(account)'],
          objective: 'Return the score of any account, zero if it never played',
          hints: [
            'Look the account up in the mapping. An address never written reads as zero, so there is no special case.',
            'A mapping is read with `get(key)`; the key here is `account`.',
            'Replace `U256::ZERO` with `self.scores.get(account)`.',
          ],
          anchor: 'pub fn score_of(',
        },
        {
          anyOf: ['self.scores.get(player) + points', 'points + self.scores.get(player)'],
          objective: "Add the points to the caller's current score",
          hints: [
            'Start from the score the caller already has: read it from the mapping before writing anything.',
            'Read the entry of `player` with `get`, then add `points` with `+`.',
            'Compute the new score with `let total = self.scores.get(player) + points;`.',
          ],
          anchor: 'pub fn record(',
        },
        {
          anyOf: ['self.scores.insert(player,', 'self.scores.setter(player).set('],
          objective: "Save the caller's new score",
          hints: [
            'Computing the total is not enough: write it back to the entry of `player`.',
            'A mapping entry is written with `insert(key, value)`, or with `setter(key).set(value)`.',
            'After computing `total`, write `self.scores.insert(player, total);`.',
          ],
          anchor: 'pub fn record(',
        },
        {
          anyOf: ['self.scores.delete(player)'],
          objective: "Remove the caller's entry from the scoreboard",
          hints: [
            'Clearing an entry resets it to zero, as if the player had never played.',
            'A mapping has a method that resets one entry: `delete(key)`.',
            'Write `self.scores.delete(player);` in `clear`.',
          ],
          anchor: 'pub fn clear(',
        },
      ],
      quizzes: [
        {
          afterStep: "Reading a mapping",
          question: "What does self.deposits.get(account) return for an address that was never written?",
          options: ["It reverts the call", "None", "U256::ZERO"],
          answer: 2,
          explanation: "Every key of a mapping exists and starts at the zero value, so get(key) on an unwritten key returns U256::ZERO (or false, or an empty value).",
        },
        {
          afterStep: "Writing and deleting",
          question: "Which call resets one entry of a mapping to zero?",
          options: ["self.members.delete(account)", "self.members.remove(account)", "self.members.get(account).clear()"],
          answer: 0,
          explanation: "delete(key) resets the entry to its zero value. take(key) does the same and also returns the old value.",
        },
      ],
    },
  },
  7: {
    slug: 'storage-vectors',
    difficulty: 'Beginner',
    preview: 'A price log you can append to, read by index and trim from the end.',
    minutes: 15,
    exercise: {
      explanation: [
        '## Storage vectors',
        '',
        'A storage vector is a dynamic array, Solidity\'s `T[]`: its elements are ordered, indexed from 0, and it knows its length. Unlike a mapping, it has an end, so you can count and list what it holds.',
        '',
        '### Declaring a vector',
        '',
        'Declare it in `sol_storage!` with Solidity syntax, the element type followed by `[]`:',
        '',
        '```rust',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Guestbook {',
        '        address[] visitors;',
        '        uint256[] visits;',
        '    }',
        '}',
        '```',
        '',
        'Each field becomes a `StorageVec` accessor: `visitors` holds `Address` values, `visits` holds `U256` values.',
        '',
        '### Length and appending',
        '',
        '| Call | Effect |',
        '|---|---|',
        '| `len()` | Returns the number of elements, as a Rust `usize`. |',
        '| `is_empty()` | Returns `true` when there are none. |',
        '| `push(value)` | Appends `value` at the end. |',
        '',
        'A public method returns numbers as `U256`, so convert the length with `U256::from(...)`:',
        '',
        '```rust',
        'pub fn sign(&mut self) {',
        '    let visitor = self.vm().msg_sender();',
        '    self.visitors.push(visitor);',
        '}',
        '',
        'pub fn count(&self) -> U256 {',
        '    U256::from(self.visitors.len())',
        '}',
        '```',
        '',
        '### Reading by index',
        '',
        '`get(index)` returns an `Option`: `Some(value)` inside the vector and `None` past its end. The index can be a `U256` or a Rust integer.',
        '',
        '```rust',
        'match self.visitors.get(index) {',
        '    Some(visitor) => visitor,',
        '    None => Address::ZERO,',
        '}',
        '```',
        '',
        'To revert instead, turn the `None` into an error with `ok_or(error)`. Returning that `Err` from a public method reverts the call:',
        '',
        '```rust',
        'pub fn visitor_at(&self, index: U256) -> Result<Address, GuestbookError> {',
        '    self.visitors.get(index).ok_or(GuestbookError::NoVisitor(NoVisitor { index }))',
        '}',
        '```',
        '',
        '### Updating and removing',
        '',
        '`setter(index)` returns `Some` writable handle for an existing element, and `None` past the end:',
        '',
        '```rust',
        'if let Some(mut visits) = self.visits.setter(index) {',
        '    let next = visits.get() + U256::from(1);',
        '    visits.set(next);',
        '}',
        '```',
        '',
        '`pop()` removes the last element and returns it, or `None` when the vector is empty. A vector only shrinks from its end: there is no call to remove an element in the middle.',
        '',
        '### Your task',
        '',
        'Build a price log:',
        '',
        '1. Give `PriceLog` a storage field called `prices` that holds a list of `uint256` prices.',
        '2. `length` returns how many prices are stored.',
        '3. `record` appends `price` at the end of the list.',
        '4. `price_at` returns the price at `index`, and reverts with `IndexOutOfBounds` when there is none.',
        '5. `remove_last` removes the most recent price.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{alloy_primitives::U256, alloy_sol_types::sol, prelude::*};',
        '',
        'sol! {',
        '    error IndexOutOfBounds(uint256 index, uint256 length);',
        '}',
        '',
        '#[derive(SolidityError)]',
        'pub enum PriceLogError {',
        '    IndexOutOfBounds(IndexOutOfBounds),',
        '}',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct PriceLog {',
        '        // TODO: add a list of uint256 prices called prices',
        '    }',
        '}',
        '',
        '#[public]',
        'impl PriceLog {',
        '    pub fn length(&self) -> U256 {',
        '        // TODO: return the number of prices',
        '        U256::ZERO',
        '    }',
        '',
        '    pub fn record(&mut self, price: U256) {',
        '        // TODO: append price to the list',
        '    }',
        '',
        '    pub fn price_at(&self, index: U256) -> Result<U256, PriceLogError> {',
        '        // TODO: return the price at index,',
        '        // or IndexOutOfBounds when index is past the end',
        '        Ok(U256::ZERO)',
        '    }',
        '',
        '    pub fn remove_last(&mut self) {',
        '        // TODO: remove the last price',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['uint256[] prices;'],
          objective: 'Keep a list of prices in the contract',
          hints: [
            'A list that grows is a storage vector, declared inside `sol_storage!` in the `PriceLog` struct.',
            'In Solidity syntax, a list of `uint256` values is the element type followed by `[]`. Name the field `prices`.',
            'Add `uint256[] prices;` inside `pub struct PriceLog { ... }`.',
          ],
          anchor: 'pub struct PriceLog {',
        },
        {
          anyOf: ['-> U256 { U256::from(self.prices.len()) }', '-> U256 { return U256::from(self.prices.len()); }'],
          objective: 'Return how many prices are stored',
          hints: [
            'The vector knows how many elements it holds: ask it instead of returning zero.',
            '`len()` returns a Rust `usize`; convert it to the `U256` the method returns with `U256::from(...)`.',
            'The body of `length` is only the conversion: `pub fn length(&self) -> U256 { U256::from(self.prices.len()) }`.',
          ],
          anchor: 'pub fn length(',
        },
        {
          anyOf: ['self.prices.push(price)'],
          objective: 'Add the new price at the end of the list',
          hints: [
            'Appending changes storage, and `record` already takes `&mut self`.',
            'A storage vector appends a value at its end with `push(value)`.',
            'Write `self.prices.push(price);` in `record`.',
          ],
          anchor: 'pub fn record(',
        },
        {
          anyOf: ['self.prices.get(index)'],
          objective: 'Read the price stored at the index',
          hints: [
            'Look the element up by its position in the vector instead of returning zero.',
            '`get(index)` returns `Some(price)` inside the vector and `None` past its end; it accepts a `U256` index.',
            'Start the body of `price_at` with `self.prices.get(index)`.',
          ],
          anchor: 'pub fn price_at(',
        },
        {
          anyOf: ['PriceLogError::IndexOutOfBounds(IndexOutOfBounds {'],
          objective: 'Revert when the index is past the end of the list',
          hints: [
            'Past the end there is no price to return: that case must revert instead of returning zero.',
            '`ok_or(error)` turns the `None` of `get` into an `Err`. Wrap an `IndexOutOfBounds` value, with the `index` and the current `length`, in the `PriceLogError::IndexOutOfBounds` variant.',
            'Make the body of `price_at` `self.prices.get(index).ok_or(PriceLogError::IndexOutOfBounds(IndexOutOfBounds { index, length: self.length() }))`.',
          ],
          anchor: 'pub fn price_at(',
        },
        {
          anyOf: ['self.prices.pop()', 'self.prices.erase_last()'],
          objective: 'Remove the most recent price',
          hints: [
            'The most recent price is the last element of the vector, and a vector shrinks from its end.',
            'A storage vector removes and returns its last element with `pop()`.',
            'Write `self.prices.pop();` in `remove_last`.',
          ],
          anchor: 'pub fn remove_last(',
        },
      ],
      quizzes: [
        {
          afterStep: "Length and appending",
          question: "Why does count() wrap the length in U256::from(...)?",
          options: ["len() returns a usize, and the method returns a U256", "len() returns the length in bytes", "Lengths over 255 would overflow otherwise"],
          answer: 0,
          explanation: "len() returns a Rust usize. Public methods use U256 for uint256, so the length is converted with U256::from.",
        },
        {
          afterStep: "Reading by index",
          question: "A vector holds 3 elements. What does get(3) return?",
          options: ["The last element", "None", "U256::ZERO"],
          answer: 1,
          explanation: "Indexes start at 0, so a vector of 3 elements has indexes 0 to 2. Past the end, get returns None instead of a zero value.",
        },
      ],
    },
  },
  8: {
    slug: 'nested-structs',
    difficulty: 'Intermediate',
    preview: 'A to-do list whose tasks are structs, stored in a vector.',
    minutes: 20,
    exercise: {
      explanation: [
        '## Nested structs',
        '',
        'Storage can group related fields in structs of your own, like Solidity `struct`s. A storage struct can be a field of the contract, the value of a mapping or the element of a vector.',
        '',
        '### Declaring structs',
        '',
        'Declare every struct in `sol_storage!`. Only the contract itself is marked `#[entrypoint]`; the others are storage types its fields can use:',
        '',
        '```rust',
        'sol_storage! {',
        '    pub struct Settings {',
        '        uint256 fee;',
        '        address treasury;',
        '    }',
        '',
        '    pub struct Member {',
        '        string name;',
        '        uint256 level;',
        '    }',
        '',
        '    #[entrypoint]',
        '    pub struct Club {',
        '        Settings settings;',
        '        mapping(address => Member) members;',
        '        Member[] history;',
        '    }',
        '}',
        '```',
        '',
        '`settings` is one struct, `members` maps an address to a whole `Member` and `history` is a vector of `Member`.',
        '',
        '### Fields of a struct',
        '',
        'Chain the field names, then read or write the last field like any other:',
        '',
        '```rust',
        'let fee = self.settings.fee.get();',
        'self.settings.fee.set(new_fee);',
        '```',
        '',
        '### Structs in mappings',
        '',
        '`get(key)` only works for simple values. For a struct, `getter(key)` returns a handle to read its fields and `setter(key)` a handle to write them:',
        '',
        '```rust',
        'let level = self.members.getter(account).level.get();',
        '',
        'let mut member = self.members.setter(account);',
        'member.name.set_str(&name);',
        'member.level.set(U256::from(1));',
        '```',
        '',
        '### Structs in vectors',
        '',
        '`push(value)` needs a plain value, and a storage struct is not one. `grow()` appends an element with every field at zero and returns a handle to fill it:',
        '',
        '```rust',
        'let mut entry = self.history.grow();',
        'entry.name.set_str(name);',
        '```',
        '',
        '`getter(index)` and `setter(index)` return the handle in an `Option`: `None` past the end of the vector. Combine them with `ok_or` and `?` to revert on a missing element:',
        '',
        '```rust',
        'let entry = self.history.getter(index).ok_or(ClubError::NoEntry(NoEntry { index }))?;',
        'let name = entry.name.get_string();',
        '```',
        '',
        '### Handles borrow the contract',
        '',
        'A handle from `setter` or `grow` keeps `self` borrowed until its last use, so the compiler refuses `self.vm()` in between. Read what you need from `self` first:',
        '',
        '```rust',
        'let account = self.vm().msg_sender();',
        'let mut member = self.members.setter(account);',
        'member.level.set(U256::from(2));',
        '```',
        '',
        '### Your task',
        '',
        'Build a to-do list:',
        '',
        '1. Give `Task` a `string` field called `title` and a `bool` field called `done`.',
        '2. Give `TodoList` a field called `tasks` that holds a list of `Task`.',
        '3. `add_task` adds a task with the given `title` at the end of the list. Tasks are numbered from 0, in the order they are added.',
        '4. `task` returns the title of task `id` and whether it is done, and reverts with `UnknownTask` when there is no such task.',
        '5. `complete` marks task `id` as done, with the same revert.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use alloc::string::String;',
        'use stylus_sdk::{alloy_primitives::U256, alloy_sol_types::sol, prelude::*};',
        '',
        'sol! {',
        '    error UnknownTask(uint256 id);',
        '}',
        '',
        '#[derive(SolidityError)]',
        'pub enum TodoError {',
        '    UnknownTask(UnknownTask),',
        '}',
        '',
        'sol_storage! {',
        '    pub struct Task {',
        '        // TODO: add a string title and a bool done',
        '    }',
        '',
        '    #[entrypoint]',
        '    pub struct TodoList {',
        '        // TODO: add a list of Task called tasks',
        '    }',
        '}',
        '',
        '#[public]',
        'impl TodoList {',
        '    pub fn add_task(&mut self, title: String) {',
        '        // TODO: add a task with this title at the end of the list',
        '    }',
        '',
        '    pub fn task(&self, id: U256) -> Result<(String, bool), TodoError> {',
        '        // TODO: look the task up, or revert with UnknownTask,',
        '        // then return its title and whether it is done',
        '        Ok((String::new(), false))',
        '    }',
        '',
        '    pub fn complete(&mut self, id: U256) -> Result<(), TodoError> {',
        '        // TODO: mark the task as done, or revert with UnknownTask',
        '        Ok(())',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['string title; bool done;', 'bool done; string title;'],
          objective: 'Give every task a title and a done flag',
          hints: [
            'A storage struct declares its fields like the contract does, with Solidity syntax, inside `pub struct Task { ... }`.',
            'The title is a `string` named `title`; the flag is a `bool` named `done`. End each declaration with a semicolon.',
            'Write `string title; bool done;` inside `pub struct Task { ... }`, one field per line.',
          ],
          anchor: 'pub struct Task {',
        },
        {
          anyOf: ['Task[] tasks;'],
          objective: 'Keep the tasks in a list',
          hints: [
            'The contract needs a vector whose elements are whole tasks.',
            'A vector field is the element type followed by `[]`; here the element type is the `Task` struct, and the field is called `tasks`.',
            'Add `Task[] tasks;` inside `pub struct TodoList { ... }`.',
          ],
          anchor: 'pub struct TodoList {',
        },
        {
          anyOf: ['self.tasks.grow()'],
          alsoAnyOf: [['.title.set_str(title)', '.title.set_str(&title)']],
          objective: 'Add a task with the given title at the end of the list',
          hints: [
            'A task is a storage struct, so it cannot be built first and pushed: the vector creates the element, then you fill its fields.',
            '`grow()` appends an element with every field at zero and returns a handle to it; keep it in a `let mut` variable. The `title` field of the handle is a `string`, written with `set_str`.',
            'Write `let mut task = self.tasks.grow();` then `task.title.set_str(title);` in `add_task`.',
          ],
          anchor: 'pub fn add_task(',
        },
        {
          // The revert is bound to the lookup, so the one in complete does not count for task.
          anyOf: [
            'self.tasks.getter(id).ok_or(TodoError::UnknownTask(UnknownTask {',
            'self.tasks.getter(id).ok_or_else(|| TodoError::UnknownTask(UnknownTask {',
          ],
          objective: 'Look a task up by its id, and revert when there is no such task',
          hints: [
            'The id of a task is its position in the vector. Past the end there is no task, and that case must revert instead of returning an empty task.',
            'For a vector of structs, `getter(index)` returns `Some` read handle, or `None` past the end. Turn the `None` into an error with `ok_or(...)`, wrapping an `UnknownTask { id }` in the `TodoError::UnknownTask` variant, and propagate it with `?`.',
            'Write `let task = self.tasks.getter(id).ok_or(TodoError::UnknownTask(UnknownTask { id }))?;`.',
          ],
          anchor: 'pub fn task(',
        },
        {
          anyOf: ['.title.get_string()'],
          alsoAnyOf: [['.done.get()']],
          objective: 'Return the title of the task and whether it is done',
          hints: [
            'Read both fields through the handle you got for the task, in the order of the tuple.',
            'A `string` field is read as a Rust `String` with `get_string()`; a `bool` field with `get()`.',
            'Return `Ok((task.title.get_string(), task.done.get()))`.',
          ],
          anchor: 'pub fn task(',
        },
        {
          anyOf: [
            'self.tasks.setter(id).ok_or(TodoError::UnknownTask(UnknownTask {',
            'self.tasks.setter(id).ok_or_else(|| TodoError::UnknownTask(UnknownTask {',
          ],
          alsoAnyOf: [['.done.set(true)']],
          objective: 'Mark the task as done, and revert when there is no such task',
          hints: [
            '`complete` changes a task, so it needs a handle that can write, then it changes the flag of the task.',
            '`setter(index)` is the writable counterpart of `getter(index)`; it also returns `None` past the end, so revert with `UnknownTask` as in `task`. A `bool` field is written with `set(value)`.',
            'Write `let mut task = self.tasks.setter(id).ok_or(TodoError::UnknownTask(UnknownTask { id }))?;` then `task.done.set(true);` before `Ok(())`.',
          ],
          anchor: 'pub fn complete(',
        },
      ],
      quizzes: [
        {
          afterStep: "Structs in mappings",
          question: "How do you read the level of the Member stored for account?",
          options: ["self.members.get(account).level", "self.members.getter(account).level.get()", "self.members[account].level"],
          answer: 1,
          explanation: "get(key) only returns simple values. getter(key) returns a read handle to the struct, and its level field is read with get().",
        },
        {
          afterStep: "Structs in vectors",
          question: "Why does a vector of structs use grow() rather than push(value)?",
          options: [
            "A storage struct is not a plain value to pass, so grow() adds an empty element and returns a handle to fill",
            "push(value) only works on vectors of addresses",
            "grow() is cheaper because it skips writing the length",
          ],
          answer: 0,
          explanation: "push needs a plain value such as a U256 or an Address. grow() appends an element with every field at zero and returns a handle to set its fields.",
        },
        {
          afterStep: "Handles borrow the contract",
          question: "Where should self.vm().msg_sender() be read when you also need self.members.setter(account)?",
          options: ["Anywhere: handles do not borrow self", "After the last use of the handle only", "Before taking the handle"],
          answer: 2,
          explanation: "The handle keeps self borrowed until its last use, so reading self.vm() in between does not compile. Read the caller first, then take the handle.",
        },
      ],
    },
  },
  9: {
    slug: 'msg-context',
    difficulty: 'Beginner',
    preview: 'A check-in book that records who called and when.',
    minutes: 15,
    exercise: {
      explanation: [
        '## Message and block context',
        '',
        'Every call comes with context: who sent it, how much ETH came with it, and the block it runs in. A Stylus contract reads it through the host, `self.vm()`, as plain Rust values.',
        '',
        '### Who is calling',
        '',
        '`msg_sender()` returns the address that called this contract: the wallet for a direct call, or the contract in between when another contract makes the call.',
        '',
        '```rust',
        'pub fn whoami(&self) -> Address {',
        '    self.vm().msg_sender()',
        '}',
        '```',
        '',
        '`tx_origin()` returns the wallet that signed the transaction, however many contracts the call went through:',
        '',
        '| Call path | `msg_sender()` in Vault | `tx_origin()` in Vault |',
        '|---|---|---|',
        '| Alice → Vault | Alice | Alice |',
        '| Alice → Router → Vault | Router | Alice |',
        '',
        '### Never authorize with tx_origin',
        '',
        'Suppose Vault lets its owner withdraw when `tx_origin()` is the owner. An attacker deploys a contract that calls Vault, and tricks the owner into calling it, for example with a fake airdrop. The owner signed the transaction, so `tx_origin()` is the owner and Vault pays the attacker. This is a phishing attack.',
        '',
        '`msg_sender()` is the attacker\'s contract in that call, so a check on it fails as it should:',
        '',
        '```rust',
        'let is_owner = self.vm().msg_sender() == owner; // right: only the owner\'s own calls',
        'let is_owner = self.vm().tx_origin() == owner; // wrong: any contract the owner calls',
        '```',
        '',
        '> Always use `msg_sender()` to decide who may do what. Never use `tx_origin()` for authorization.',
        '',
        '### Block and chain',
        '',
        '| Call | Returns |',
        '|---|---|',
        '| `block_timestamp()` | `u64`: Unix time in seconds, a bounded estimate of when the sequencer sequenced the transaction |',
        '| `block_number()` | `u64`: on Arbitrum, a bounded estimate of the L1 (Ethereum) block number at which the sequencer sequenced the transaction, not the Arbitrum block number |',
        '| `chain_id()` | `u64`: the chain id, 421614 on Arbitrum Sepolia |',
        '| `contract_address()` | `Address`: the address of this contract |',
        '| `msg_value()` | `U256`: the wei sent with the call (lesson 11) |',
        '',
        '> `block_number()` follows Ethereum blocks, which are much slower than Arbitrum blocks: many Arbitrum blocks report the same number.',
        '',
        'Storage holds `uint256` values, so convert a `u64` with `U256::from`:',
        '',
        '```rust',
        'let opened_in = U256::from(self.vm().block_number());',
        '```',
        '',
        '### Storing an address',
        '',
        'An `address` field holds one `Address`. `get()` reads it, `Address::ZERO` until it is written, and `set(value)` writes it:',
        '',
        '```rust',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Door {',
        '        address last_opener;',
        '        uint256 opened_in;',
        '    }',
        '}',
        '',
        '#[public]',
        'impl Door {',
        '    pub fn open(&mut self) {',
        '        let opener = self.vm().msg_sender();',
        '        self.last_opener.set(opener);',
        '        self.opened_in.set(U256::from(self.vm().block_number()));',
        '    }',
        '}',
        '```',
        '',
        '### Your task',
        '',
        'Build a check-in book:',
        '',
        '1. Give `Attendance` a storage field called `last_visitor` that holds an address.',
        '2. In `check_in`, read the caller into `visitor` and the current block time, as a `U256`, into `now`.',
        '3. Record `now` as the check-in time of `visitor` in `check_ins`, and make `visitor` the last visitor.',
        '4. `checked_in_at` returns the check-in time of `account`.',
        '5. `last_visitor` returns the last visitor.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{',
        '    alloy_primitives::{Address, U256},',
        '    prelude::*,',
        '};',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct Attendance {',
        '        mapping(address => uint256) check_ins;',
        '        // TODO: add the address of the last visitor',
        '    }',
        '}',
        '',
        '#[public]',
        'impl Attendance {',
        '    pub fn check_in(&mut self) {',
        '        // TODO: read the caller and the block time, then record the check-in',
        '    }',
        '',
        '    pub fn checked_in_at(&self, account: Address) -> U256 {',
        '        // TODO: return the check-in time of account',
        '        U256::ZERO',
        '    }',
        '',
        '    pub fn last_visitor(&self) -> Address {',
        '        // TODO: return the last visitor',
        '        Address::ZERO',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['address last_visitor;'],
          objective: 'Store the address of the last visitor',
          hints: [
            'One address is a storage field of its own, next to `check_ins` in `sol_storage!`.',
            'The Solidity type is `address` and the field is called `last_visitor`.',
            'Add `address last_visitor;` inside `pub struct Attendance { ... }`.',
          ],
          anchor: 'pub struct Attendance {',
        },
        {
          anyOf: ['let visitor = self.vm().msg_sender();'],
          objective: 'Find out who is checking in',
          hints: [
            'The account that called the contract comes from the host, `self.vm()`.',
            'Use `msg_sender()`, not `tx_origin()`: it is the direct caller, the one to trust.',
            'Start `check_in` with `let visitor = self.vm().msg_sender();`.',
          ],
          anchor: 'pub fn check_in(',
        },
        {
          anyOf: ['let now = U256::from(self.vm().block_timestamp());'],
          objective: 'Read the current block time as a 256-bit number',
          hints: [
            'The host also knows the block the call runs in, including its time.',
            '`block_timestamp()` returns a `u64`; storage holds `U256`, so convert it with `U256::from`.',
            'Write `let now = U256::from(self.vm().block_timestamp());`.',
          ],
          anchor: 'pub fn check_in(',
        },
        {
          anyOf: ['self.check_ins.insert(visitor, now)', 'self.check_ins.setter(visitor).set(now)'],
          objective: "Record the visitor's check-in time",
          hints: [
            'Write the time into the `check_ins` mapping, under the visitor.',
            'A mapping entry is written with `insert(key, value)`, or with `setter(key).set(value)`.',
            'Write `self.check_ins.insert(visitor, now);`.',
          ],
          anchor: 'pub fn check_in(',
        },
        {
          anyOf: ['self.last_visitor.set(visitor)'],
          objective: 'Make the caller the last visitor',
          hints: [
            'The last visitor changes on every check-in.',
            'An `address` field is written with `set(value)`.',
            'Write `self.last_visitor.set(visitor);`.',
          ],
          anchor: 'pub fn check_in(',
        },
        {
          anyOf: ['self.check_ins.get(account)'],
          objective: 'Return when an account checked in, zero if it never did',
          hints: [
            'Look the account up in `check_ins`. An account that never checked in reads as zero.',
            'A mapping is read with `get(key)`; the key is `account`.',
            'Replace `U256::ZERO` with `self.check_ins.get(account)`.',
          ],
          anchor: 'pub fn checked_in_at(',
        },
        {
          anyOf: ['self.last_visitor.get()'],
          objective: 'Return the last visitor',
          hints: [
            'Read the stored address instead of returning the zero address.',
            'An `address` field is read with `get()`.',
            'Replace `Address::ZERO` with `self.last_visitor.get()`.',
          ],
          anchor: 'pub fn last_visitor(',
        },
      ],
      quizzes: [
        {
          afterStep: "Who is calling",
          question: "Alice calls a Router contract, which calls Vault. What does self.vm().msg_sender() return inside Vault?",
          options: ["Alice", "Router", "Vault"],
          answer: 1,
          explanation: "msg_sender() is the direct caller of the current contract: Router. tx_origin() would return Alice, who signed the transaction.",
        },
        {
          afterStep: "Never authorize with tx_origin",
          question: "Why must a contract never check tx_origin() == owner to authorize a call?",
          options: [
            "Any contract the owner is tricked into calling can pass the check",
            "tx_origin() is not available in Stylus",
            "tx_origin() changes with every block",
          ],
          answer: 0,
          explanation: "The owner signed the transaction, so tx_origin() is the owner even inside a malicious contract's call. Check msg_sender() instead: it is the malicious contract.",
        },
        {
          afterStep: "Block and chain",
          question: "On Arbitrum, what does self.vm().block_number() return?",
          options: [
            "The number of the current Arbitrum block",
            "The number of transactions in the current block",
            "An estimate of the L1 block number at which the sequencer sequenced the transaction",
          ],
          answer: 2,
          explanation: "On Arbitrum, block_number() is a bounded estimate of the Ethereum (L1) block number, so many Arbitrum blocks report the same number.",
        },
      ],
    },
  },
  10: {
    slug: 'access-control',
    difficulty: 'Intermediate',
    preview: 'A fee setting that only its owner can change or hand over.',
    minutes: 15,
    exercise: {
      explanation: [
        '## Access control',
        '',
        'Anyone can call any public method of a contract. To keep a method for some accounts only, the contract checks the caller, `self.vm().msg_sender()`, and reverts for everyone else. The most common pattern is a single owner.',
        '',
        '### Setting the owner at deployment',
        '',
        'A method marked `#[constructor]` runs once, when the contract is deployed; the SDK makes sure it can never run again. Its parameters are passed at deployment.',
        '',
        'With `cargo stylus deploy`, deployment goes through a contract called StylusDeployer, so `msg_sender()` inside the constructor is StylusDeployer, not you. Pass the owner as a parameter instead:',
        '',
        '```rust',
        '#[constructor]',
        'pub fn constructor(&mut self, admin: Address) {',
        '    self.admin.set(admin);',
        '}',
        '```',
        '',
        '### A private guard',
        '',
        'The same check guards several methods, so write it once, as a helper. Every method of a `#[public]` block is in the contract ABI, even without `pub`, so put the helper in a plain `impl` block, where it stays internal:',
        '',
        '```rust',
        'impl Treasury {',
        '    fn only_admin(&self) -> Result<(), TreasuryError> {',
        '        let caller = self.vm().msg_sender();',
        '        if caller != self.admin.get() {',
        '            return Err(TreasuryError::NotAdmin(NotAdmin { caller }));',
        '        }',
        '        Ok(())',
        '    }',
        '}',
        '```',
        '',
        '`NotAdmin` is a `sol!` error wrapped in `TreasuryError`, as in lesson 3. Naming the caller in the error tells callers who was refused.',
        '',
        '### Guarding with ?',
        '',
        'The `?` operator returns the error of a `Result` early. In a `#[public]` method, that error reverts the call:',
        '',
        '```rust',
        'pub fn set_limit(&mut self, limit: U256) -> Result<(), TreasuryError> {',
        '    self.only_admin()?;',
        '    self.limit.set(limit);',
        '    Ok(())',
        '}',
        '```',
        '',
        'Call the guard first, before the method reads or writes anything else.',
        '',
        '### Handing over ownership',
        '',
        'An owner can hand the contract to another account by writing a new owner, behind the same guard. From then on, the old owner is refused like anyone else.',
        '',
        '> Handing the contract to `Address::ZERO` locks the guarded methods for good: nobody can call as the zero address. Double-check the new owner.',
        '',
        '### Your task',
        '',
        '`FeeConfig` keeps a fee that only its owner may change. The `Unauthorized` error is declared for you.',
        '',
        '1. The constructor makes `owner` the owner of the contract.',
        '2. `only_owner` reads the caller into `caller` and reverts with `Unauthorized` unless it is the owner.',
        '3. `set_fee` and `transfer_ownership` call `only_owner` before they write anything.',
        '',
        'Stuck? Each objective has hints, from a nudge to the exact code.',
      ].join('\n'),
      starterCode: [
        '#![cfg_attr(not(any(test, feature = "export-abi")), no_main)]',
        'extern crate alloc;',
        '',
        'use stylus_sdk::{',
        '    alloy_primitives::{Address, U256},',
        '    alloy_sol_types::sol,',
        '    prelude::*,',
        '};',
        '',
        'sol! {',
        '    error Unauthorized(address caller);',
        '}',
        '',
        '#[derive(SolidityError)]',
        'pub enum AccessError {',
        '    Unauthorized(Unauthorized),',
        '}',
        '',
        'sol_storage! {',
        '    #[entrypoint]',
        '    pub struct FeeConfig {',
        '        address owner;',
        '        uint256 fee;',
        '    }',
        '}',
        '',
        '#[public]',
        'impl FeeConfig {',
        '    #[constructor]',
        '    pub fn constructor(&mut self, owner: Address) {',
        '        // TODO: make owner the owner of the contract',
        '    }',
        '',
        '    pub fn owner(&self) -> Address {',
        '        self.owner.get()',
        '    }',
        '',
        '    pub fn fee(&self) -> U256 {',
        '        self.fee.get()',
        '    }',
        '',
        '    pub fn set_fee(&mut self, fee: U256) -> Result<(), AccessError> {',
        '        // TODO: only the owner may change the fee',
        '        self.fee.set(fee);',
        '        Ok(())',
        '    }',
        '',
        '    pub fn transfer_ownership(&mut self, new_owner: Address) -> Result<(), AccessError> {',
        '        // TODO: only the owner may hand over the contract',
        '        self.owner.set(new_owner);',
        '        Ok(())',
        '    }',
        '}',
        '',
        'impl FeeConfig {',
        '    fn only_owner(&self) -> Result<(), AccessError> {',
        '        // TODO: revert with Unauthorized unless the caller is the owner',
        '        Ok(())',
        '    }',
        '}',
      ].join('\n'),
      checks: [
        {
          anyOf: ['self.owner.set(owner)'],
          objective: 'Store the owner chosen at deployment',
          hints: [
            'The constructor receives the owner as a parameter: write it to the `owner` field.',
            'An `address` field is written with `set(value)`. Do not use `msg_sender()` here: during deployment it is StylusDeployer.',
            'Write `self.owner.set(owner);` in the constructor.',
          ],
          anchor: 'pub fn constructor(',
        },
        {
          anyOf: ['let caller = self.vm().msg_sender();'],
          objective: 'Find out who is calling',
          hints: [
            'The guard needs the account that called the contract.',
            'Read it from the host with `msg_sender()`, never `tx_origin()`.',
            'Start `only_owner` with `let caller = self.vm().msg_sender();`.',
          ],
          anchor: 'fn only_owner(',
        },
        {
          anyOf: ['if caller != self.owner.get() {', 'if self.owner.get() != caller {'],
          objective: 'Compare the caller with the owner',
          hints: [
            'Read the stored owner and compare it with `caller`.',
            'An `address` field is read with `get()`; refuse when the two differ, with `!=`.',
            'Write `if caller != self.owner.get() { ... }`.',
          ],
          anchor: 'fn only_owner(',
        },
        {
          anyOf: ['Err(AccessError::Unauthorized(Unauthorized { caller }))'],
          objective: 'Refuse every caller but the owner',
          hints: [
            'Returning an `Err` from the guard makes every method that uses it revert.',
            'Wrap an `Unauthorized { caller }` value in the `AccessError::Unauthorized` variant.',
            'Inside the `if`, write `return Err(AccessError::Unauthorized(Unauthorized { caller }));`.',
          ],
          anchor: 'fn only_owner(',
        },
        {
          anyOf: ['self.only_owner()?; self.fee.set(fee);'],
          objective: 'Let only the owner change the fee',
          hints: [
            'Call the guard at the start of `set_fee`, before the fee is written.',
            'The guard returns a `Result`: add `?` so its error returns early and reverts the call.',
            'Make `set_fee` start with `self.only_owner()?; self.fee.set(fee);`.',
          ],
          anchor: 'pub fn set_fee(',
        },
        {
          anyOf: ['self.only_owner()?; self.owner.set(new_owner);'],
          objective: 'Let only the owner hand over the contract',
          hints: [
            'The new owner must not be written before the current owner is checked.',
            'Use the same guard as `set_fee`, with `?`, as the first line.',
            'Make `transfer_ownership` start with `self.only_owner()?; self.owner.set(new_owner);`.',
          ],
          anchor: 'pub fn transfer_ownership(',
        },
      ],
      quizzes: [
        {
          afterStep: "Setting the owner at deployment",
          question: "Why does the constructor take the owner as a parameter instead of reading msg_sender()?",
          options: [
            "msg_sender() is not available in a constructor",
            "With cargo stylus deploy, the constructor is called by StylusDeployer, so msg_sender() is StylusDeployer",
            "A constructor cannot write to storage",
          ],
          answer: 1,
          explanation: "Deployment goes through the StylusDeployer contract, which calls the constructor. Reading msg_sender() there would make StylusDeployer the owner.",
        },
        {
          afterStep: "A private guard",
          question: "Where should a helper like only_owner go so that it is not part of the contract ABI?",
          options: [
            "In the #[public] block, without pub",
            "In the #[public] block, marked #[constructor]",
            "In a plain impl block, without #[public]",
          ],
          answer: 2,
          explanation: "Every method of a #[public] block is exported, pub or not. A plain impl block stays internal Rust code.",
        },
        {
          afterStep: "Guarding with ?",
          question: "In set_limit, what happens when self.only_admin()? meets an Err?",
          options: [
            "The method returns the error and the call reverts",
            "The error is logged and the limit is still written",
            "The contract panics and burns all the gas",
          ],
          answer: 0,
          explanation: "? returns the error early. Returning Err from a #[public] method reverts the call with the ABI-encoded error.",
        },
      ],
    },
  },
  11: {
    slug: 'payable-eth',
    difficulty: 'Intermediate',
    preview: 'A piggy bank that takes ETH deposits and pays them back on request.',
    minutes: 20,
  },
};

/** Every lesson of curriculum/lessons.json, in curriculum order, merged with its web content. */
export const LESSONS: Lesson[] = curriculum.map(({ id, name, xp, available, module }): Lesson => {
  const content = CONTENT[id];
  if (!content) {
    throw new Error(`Lesson ${id} is in curriculum/lessons.json but has no web content`);
  }
  if (!modules.some((entry) => entry.id === module)) {
    throw new Error(`Lesson ${id} belongs to an unknown module: ${module}`);
  }
  const { slug, difficulty, preview, minutes } = content;
  const base = { id, slug, title: name, difficulty, xp, module, preview, minutes };
  if (!available) {
    return { ...base, available: false };
  }
  if (!content.exercise) {
    throw new Error(`Lesson ${id} is available but has no exercise`);
  }
  return { ...base, available: true, exercise: content.exercise };
});

export function getLesson(slug: string): Lesson | undefined {
  return LESSONS.find((lesson) => lesson.slug === slug);
}
